import { createSlice,createAsyncThunk } from "@reduxjs/toolkit";
import appwriteService from "../appwrite/config";
// import React,{useEffect} from "react";

const initialState={
    posts:[],
    loading:false,
    error:null,
}

export const fetchPosts=createAsyncThunk("posts/fetchPosts",async ()=>{
        console.log("fetchPosts post slice");
        const postsData=await appwriteService.getPosts([]).then(res=>{
            console.log(res);
            return res;
        });
        // const postsDataa=await postsData.json();
        console.log("fetchPosts post slice",postsData);
        return postsData;
})

const postsSlice=createSlice({
    name: 'posts',
    initialState,
    reducers:{
        /**
 * state refers to the entire Redux store, which contains all the slices of state from different parts of your application.
 * 
 */
        allPosts:(state,action)=>{
            console.log("//////////////////////////",action);
            state.posts=action.payload.posts;
        }
    },
    /**
     * 
     * In Redux Toolkit, extraReducers is used in a createSlice to handle actions that are defined outside of the slice. In your case, fetchPosts is an asynchronous action created with createAsyncThunk. Since fetchPosts is not defined inside the slice's reducers section, it needs to be handled by extraReducers.

Key Use Cases of extraReducers:
Handle actions generated by createAsyncThunk.
Handle actions from other slices or custom actions that are dispatched to this slice.
Example:
In your postsSlice, extraReducers is used to handle the different states (pending, fulfilled, rejected) of the fetchPosts async action.} builder 
     */
    extraReducers: (builder) => {
        builder
            .addCase(fetchPosts.pending, (state) => {
                // Optionally, set a loading state here
                state.loading=true;
            })
            .addCase(fetchPosts.fulfilled, (state, action) => {
                console.log("posts fetched:", action.payload);
                state.posts = action.payload;
                state.loading=false;
                // Update state with fetched posts
            })
            .addCase(fetchPosts.rejected, (state, action) => {
                state.error=action.error;
                console.error("Failed to fetch posts", action.error);
                // Optionally, handle errors here
            });
    }

})

export default postsSlice.reducer;

/**
 * What is builder?
The builder is an object provided by createSlice that helps you add cases (handlers) for actions. It is a utility provided by Redux Toolkit to create handlers for different action types without using a switch-case structure. You use builder.addCase() to specify how the slice should respond to different action states.

How builder Works:
builder.addCase takes two arguments:
Action type: It listens for this action (like fetchPosts.pending).
Reducer function: Defines how the state should be updated when this action is dispatched.
For example:

builder.addCase(fetchPosts.pending) is fired when the fetchPosts async action is in progress.
builder.addCase(fetchPosts.fulfilled) is fired when the fetchPosts async action completes successfully and returns data.
builder.addCase(fetchPosts.rejected) is fired when the fetchPosts async action fails.
Where do extraReducers and builder come from?
extraReducers is a special key in the configuration object passed to createSlice. It's a property provided by Redux Toolkit for handling external actions (like those created by createAsyncThunk or other actions outside the slice).

builder is provided as an argument to the function inside extraReducers. It’s part of the Redux Toolkit's API to help with the composition of reducers in a more fluent and readable manner.

Why not use reducers?
reducers in a slice are used to define synchronous actions that are local to that slice (i.e., the action creators are auto-generated for them).

extraReducers, on the other hand, is used when you need to handle actions from outside the slice, like fetchPosts created by createAsyncThunk.

Full Example Breakdown:
 */